service CameraService:
    wait-started: 10 ms         # optional, next service will wait until current completely started plus specified time
    camera:
        from-path: frames/
        fps: Max                    # Max / Min / 30.0
        resolution: 
            width: 1200
            height: 800
        index: 0
        # address: 192.168.10.12:2020
        # Mono8/10/12/16, Bayer8/10/12/16, RGB8, BGR8, YCbCr8, YCbCr411, YUV422, YUV411 | Default and fastest BayerRG8
        # pixel-format:  Mono8
        # pixel-format:  BayerRG8
        # pixel-format:  QOI_Mono8
        pixel-format:  QOI_BayerRG8
        exposure:
            auto: Off                   # Off / Continuous
            time: 26000                   # microseconds
        auto-packet-size: true          # StreamAutoNegotiatePacketSize
        channel-packet-size: Max        # Maximizing packet size increases frame rate
        resend-packet: true             # StreamPacketResendEnable
    image:
        cropping:
            x: 10           # new left edge
            width: 1900     # new image width
            y: 10           # new top edge
            height: 1180    # new image height
        gamma:
            factor: 99.0            # percent of influence of [AutoGamma] algorythm bigger the value more the effect of [AutoGamma] algorythm, %
        brightness-contrast:
            hist-clip-left: 0.0     # optional histogram clipping from right, default = 0.0 %
            hist-clip-right: 0.0    # optional histogram clipping from right, default = 0.0 %
        gausian:
            blur-size:              # blur radius
                width: 3
                height: 3
            sigma-x: 0.0
            sigma-y: 0.0
        sobel:
            kernel-size: 3
            scale: 1.0
            delta: 0.0
        overlay:
            src1-weight: 0.5
            src2-weight: 0.5
            gamma: 0.0
    template-match:
        template: template_128.png
        threshold: 0.8
        method: TM_CCOEFF_NORMED    # TM_CCOEFF_NORMED or TM_CCORR_NORMED recomended, 
